name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    strategy:
      matrix:
        node-version: ["20.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run build-only

      - name: Install Zip
        uses: montudor/action-zip@v0.1.1

      - name: Zip Dist as Artifact (at root /)
        run: |
          cd ./dist
          echo "Compressing these files:"
          ls -al
          zip -qq -r -T ../../vue-primevue.zip *

      - name: Save Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: vue-primevue.zip
          path: vue-primevue.zip
          if-no-files-found: error

  deploy-web-production:
    needs: [build]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: vue-primevue.zip

      - name: Upload Artifact over SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          overwrite: true
          source: "vue-primevue.zip"
          target: "~/artifacts"

      - name: Enter SSH and unzip Artifact
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            unzip -o ~/artifacts/vue-primevue.zip -d /var/www/prsevero.com.br/vue-primevue/
