name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20.9"]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run build-only

      - name: Install Zip
        uses: montudor/action-zip@v1

      - name: Zip Dist as Artifact (at root /)
        run: |
          cd ./dist
          echo "Compressing these files:"
          ls -al
          zip -qq -r -T ../vue-primevue.zip *

      - name: Save Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: vue-primevue.zip
          path: vue-primevue.zip
          if-no-files-found: error

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@master
        with:
          name: vue-primevue.zip

      - name: Upload Artifact over SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          overwrite: true
          source: "vue-primevue.zip"
          target: "~/artifacts"

      - name: Enter SSH and unzip Artifact
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            unzip -o ~/artifacts/vue-primevue.zip -d /var/www/prsevero.com.br/vue-primevue/
